return {
	require("plugin_configs.onedarkpro"),
	require("plugin_configs.fuzzy_finder.telescope"),
	require("plugin_configs.better_ui"),
	require("plugin_configs.tree_sitter"),
	require("plugin_configs.file_tree"),
	require("plugin_configs.statusline.lualine"),
	require("plugin_configs.vim_game"),
	require("plugin_configs.mason.mason"),
	require("plugin_configs.dashboard"),
	require("plugin_configs.auto_completions"),
	require("plugin_configs.lsp_signatures"),
	require("plugin_configs.git_signs"),
	require("plugin_configs.colorizer"),
	require("plugin_configs.terminal"),
	require("plugin_configs.markdown_previewer"),
	require("plugin_configs.indent_blankline"),
	require("plugin_configs.auto_pairs"),

	require("plugin_configs.mini_nvim.icons"),
	require("plugin_configs.mini_nvim.trailspace"),
}
