[General]
UITheme=theme-dark
appdata="@ByteArray(eyJ1c2VybmFtZSI6ImFidWJha3IiLCJkb2NvcGVubW9kZSI6ImVkaXQiLCJyZXN0YXJ0IjpmYWxzZSwibGFuZ2lkIjoiZW4tVVMiLCJ1aXNjYWxpbmciOiIxMjUiLCJ1aXRoZW1lIjoidGhlbWUtZGFyayIsImVkaXRvcndpbmRvd21vZGUiOmZhbHNlLCJydGwiOmZhbHNlLCJ1c2VncHUiOmZhbHNlfQ==)"
editorWindowMode=false
forcedRtl=false
position=@Rect(0 0 1920 1054)
titlebar=custom
