#!/usr/bin/env bash

hide_function() {
	local path=$1
	local apps_to_hide_file=$2

	# for app in "${apps_to_hide_array[@]}"; do
	while IFS= read -r app; do
		local file="${path}/${app}.desktop"

		# If file exists, and if the last line is not 'Hidden=true'
		if [[ -e "$file" && $(tail -1 "$file") != "Hidden=true" ]]; then
			# Appends to the file, with sudo permissions
			echo -e "\nHidden=true" | sudo tee -a "$file" >/dev/null
		fi
	done <"$apps_to_hide_file"
}

hide_function "/usr/share/applications" "$SCRIPTS/hide_apps/apps_to_hide_root.txt"
hide_function "${XDG_DATA_HOME:-$HOME/.local/share}/applications" "$SCRIPTS/hide_apps/apps_to_hide_local.txt"
