#!/usr/bin/zsh

$AUR_HELPER -Syu
paru --clean

flatpak update
flatpak uninstall --unused

ya pack -u
npm update -g
pipx upgrade-all

hide_from_menu
apply_mysql_workbench_theme.sh

source /usr/share/zinit/zinit.zsh
zinit update

# orphans=$($AUR_HELPER -Qdtq)
#
# if [[ -n "$orphans" ]]; then
# 	# shellcheck disable=SC2086
# 	$AUR_HELPER -Rns $orphans
# fi

# This script is not responsible for updating Neovim
