#!/bin/bash
#!/bin/fish

$AUR_HELPER -Syu
hide_from_menu
apply_mysql_workbench_theme.sh
flatpak update
fisher update
ya pack -u

orphans=$($AUR_HELPER -Qdtq)

if [[ -n "$orphans" ]]; then
	# shellcheck disable=SC2086
	$AUR_HELPER -Rns $orphans
fi

# This script is not responsible for updating Neovim
