profile=high-quality
volume-max=150
save-watch-history
save-position-on-quit
keep-open=always

# Fixes Pipewire issue by switching to Pulse Audio for now
# ao=pulse

# Keeps the "past" video in RAM so you can rewind instantly
demuxer-max-back-bytes=200MiB

# Uses your hardware to help play videos smoothly
hwdec=vaapi
vo=gpu
