#!/usr/bin/zsh

$AUR_HELPER -Syu
pacman -Qtdq | pacman -Rns -
paru --clean

flatpak update
flatpak uninstall --unused

npm update -g
pipx upgrade-all

hide_from_menu

source "$ZINIT_HOME/zinit.zsh"
zinit self-update
zinit update

# This script is not responsible for updating Neovim
