#!/usr/bin/zsh

$AUR_HELPER -Syu --noconfirm
pacman -Qtdq | pacman -Rns --noconfirm -
paru --clean --noconfirm

flatpak update --assumeyes
flatpak uninstall --unused --assumeyes

npm update -g
pipx upgrade-all

rustup update

hide_from_menu

source "$ZINIT_HOME/zinit.zsh"
zinit self-update
zinit update

# This script is not responsible for updating Neovim
