##################################
### Window And Workspace Rules ###
##################################

windowrule {
	name = Transparent Terminal
    match:class = ^(foot)$
    opacity = 0.8
}

windowrule {
	name = Opaque Neovim # (Overrides general Terminal rule)
    match:class = ^(foot)$
    match:title = .*( nvim)$
    opacity = 1.0
}

windowrule {
	name = 'Picture-in-Picture' Mode
    match:title = ^(Picture in picture)$
    float = on
    pin = on
    size = monitor_w*0.25 monitor_h*0.25
    move = monitor_w*0.744 monitor_h*0.012
    border_color = rgba(595959aa)
}

windowrule {
	name = Thunderbird Specifications # (Floating all windows except the main one)
    match:class = ^(thunderbird)$
    match:title = ^(?!(Mozilla Thunderbird)$)$
    float = on
    size = monitor_w*0.5 monitor_h*0.5
    border_color = rgba(595959aa)
}

windowrule {
	name = Makes Calculator a floating window
    match:class = ^(qalculate-gtk)$
    float = on
    size = 448 497
	move = monitor_w*0.5-400 monitor_h*0.5-400
}

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule {
	name = "no_gaps_when_only" behavior
    match:workspace = w[tv1]
    match:float = off
    border_size = 0
    rounding = 0
}
windowrule {
	name = "no_gaps_when_only" behavior
    match:workspace = f[1]
    match:float = off
    border_size = 0
    rounding = 0
}

windowrule {
	name = "showmethekey" Specifications
    match:class = ^(one.alynx.showmethekey)$
    float = on
}

windowrule {
	name = "showmethekey" Specifications
    match:class = ^(showmethekey-gtk)$
    float = on
    no_focus = on
    pin = on
    size = monitor_w*1 60
    move = 0 monitor_h*0.9
}
