################
### MONITORS ###
################

monitor=,1920x1080@60,auto,1

####################
### MY VARIABLES ###
####################

# Set programs that you use
$terminal = foot
$browser = firefox
$fileManager = yazi # use 'yy' in terminal to change directory when exiting

$appLauncher = ~/.config/wofi/scripts/appLauncher.sh
$appLauncherAlt = ~/.config/rofi/scripts/appLauncher.sh
$powerMenu = ~/.config/wofi/scripts/powerMenu.sh
$wifiMenu = ~/.config/wofi/scripts/wifiMenu.sh
$calculator = wofi-calc
$emojiMenu = ~/.config/wofi/scripts/emojiMenu.sh
$screenshot = ~/.config/wofi/scripts/screenshot.sh

#################
### AUTOSTART ###
#################

#exec = waybar
exec-once = waybar
exec-once = swww-daemon		# Wallpaper daemon
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # Authentication Agent 
exec-once = hypridle
exec-once = foot --server

## Startup Apps ##

exec-once = whatsapp-for-linux
#exec-once = pcloud     # Nevermind, becuase I'll have to login every time

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvdia
env = NVD_BACKEND,direct


#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    #col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg # default
    col.active_border = rgba(00ff99ee) rgba(33ccffee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = true 

    layout = dwindle	(dwindle/master)
}

decoration {
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
   
    blur {
        enabled = true
    }
}

animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
    force_split = 2
    no_gaps_when_only = 1
}

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.1 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
	scroll_factor = 0.3
	tap_button_map = lmr
	#tap-and-drag = 1
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
    workspace_swipe_min_fingers = true
    workspace_swipe_distance = 700
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

source = ~/.config/hypr/keybindings.conf

source = ~/.config/hypr/rules.conf

#############
### OTHER ###
#############

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = false
    enable_swallow = true
    swallow_regex = ^(foot)$
    swallow_exception_regex = ^(wev)$
}
