###################################
### WINDOWS AND WORKSPACE RULES ###
###################################

windowrulev2 = opacity 0.9 0.75, class:(foot)					# Makes Foot terminal transparent

windowrulev2 = opacity 0.94, class:(foot), title:^(nvim|Yazi)	# Makes Nvim and Yazi 94% transparent
windowrulev2 = noblur, class:(foot), title:^(?!(nvim|Yazi))		# Leaves Nvim and Yazi with a blured background

windowrulev2 = float, title:(Picture-in-Picture)
windowrulev2 = pin, title:(Picture-in-Picture)
windowrulev2 = size 25%, title:(Picture-in-Picture)
windowrulev2 = move 74.4% 1.2%, title:(Picture-in-Picture)		# Top Right
#windowrulev2 = move 74.4% 71.5%, title:(Picture-in-Picture)		# Bottom Right
windowrulev2 = bordercolor rgba(595959aa), title:(Picture-in-Picture)

windowrulev2 = float, class:(com.example.Dodecogon-Of-Fifths)

windowrulev2 = float, class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)
windowrulev2 = size 50%, class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)
windowrulev2 = bordercolor rgba(595959aa), class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)
