#####################
## Background Apps ##
#####################

exec-once = waybar
exec-once = swww-daemon		# Wallpaper daemon
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # Authentication Agent 
exec-once = hypridle
exec-once = foot --server

##################
## Startup Apps ##
##################

exec-once = whatsapp-for-linux
exec-once = pcloud
exec-once = webcord
