#############
### OTHER ###
#############

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = false
    enable_swallow = true
    swallow_regex = ^(foot)$
    swallow_exception_regex = ^(wev)$
}
