###################################
### Window And Workspace Rules ###
###################################

windowrulev2 = opacity 0.9 0.75, class:(foot)	# Makes Foot terminal transparent
windowrulev2 = noblur, class:(foot)	# Temporary rule

# Prevents the specified windows from becoming transparent
windowrulev2 = opacity 1, class:(foot), title:^(nvim).*

windowrulev2 = opacity 0.94, class:(foot), title:^(Yazi).*	# Makes Yazi 94% transparent
windowrulev2 = noblur, class:foot, title:^(?!(Yazi)).*		# Leaves Yazi with a blured background  # Doesn't work right now

windowrulev2 = float, title:(Picture-in-Picture)
windowrulev2 = pin, title:(Picture-in-Picture)
windowrulev2 = size 25%, title:(Picture-in-Picture)
windowrulev2 = move 74.4% 1.2%, title:(Picture-in-Picture)	# Top Right
windowrulev2 = bordercolor rgba(595959aa), title:(Picture-in-Picture)

windowrulev2 = float, class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)
windowrulev2 = size 50%, class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)
windowrulev2 = bordercolor rgba(595959aa), class:(thunderbird), initialTitle:^(?!(Mozilla Thunderbird)$)

windowrulev2 = float, class:(qalculate-gtk)
windowrulev2 = size(448,497), class:(qalculate-gtk)

# Replaces "no_gaps_when_only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# Temporary
windowrulev2 = float, class:(Tk)
