[flavor]
dark = "onedark"
# dark = "tokyo-night"
# dark = "catppuccin-mocha"

[manager]
preview_hovered = { bg = "#282C34" } # To match the "hovered" setting in the "onedark.yazi" flavor

[icon]

# Order Matters. The 1st match gets applied
globs = [
	{ name = "/home/**/.git*", text = "󰊢" },

	{ name = "/home/*/.config/vim/*", text = "" },
	{ name = "/home/*/.config/vlc/*", text = "󰕼" },
	{ name = "/home/*/.config/zsh/*", text = "󱆃" },

	{ name = "/home/*/.config/hypr/**", text = "" },

	{ name = "/home/*/.config/**/*rc", text = "" },
]

files = [
	{ name = ".editorconfig", text = "" },
	{ name = ".styluaignore", text = "" },
	{ name = ".zshenv", text = "󱆃" },

	{ name = "LICENSE", text = "" },
	{ name = "README.md", text = "" },
	{ name = "config", text = "" },
]

exts = [
	# General Info
	{ name = "txt", text = "" },
	{ name = "md", text = "" },

	# Image
	{ name = "gif", text = "" },
	{ name = "jpeg", text = "" },
	{ name = "jpg", text = "" },
	{ name = "png", text = "" },
	{ name = "webp", text = "" },

	# Video
	{ name = "avi", text = ""},
	{ name = "mkv", text = ""},
	{ name = "mp4", text = ""},
	{ name = "webm", text = ""},

	# Shell
	{ name = "sh", text = "" },

	# Binary
	{ name = "bin", text = "" },
	{ name = "o", text = "" },
	{ name = "out", text = "" },

	# C Language
	{ name = "c", text = "󰙱" },

	# C++ Language
	{ name = "cpp", text = "󰙲" },
	{ name = "c++", text = "󰙲" },
	{ name = "cc", text = "󰙲" },
	{ name = "cxx", text = "󰙲" },

	# Web Development
	{ name = "html", text = ""},
	{ name = "css", text = ""},
	{ name = "js", text = ""},

	# Other Languages
	{ name = "java", text = "" },
	{ name = "lua", text = ""},
	{ name = "py", text = "" },
	{ name = "rs", text = "" },

	# Header files for C and C++
	{ name = "h", text = "" },

	# Executables of a different OS
	{ name = "exe", text = "" },
	{ name = "app", text = "" },

	# Office Related
	{ name = "docx", text = "󱎒"},
	{ name = "pdf", text = ""},
	{ name = "xlsx", text = "󱎏"},

	# Data Serialization Formats
	{ name = "csv", text = ""},
	{ name = "ini", text = ""},
	{ name = "json", text = ""},
	{ name = "jsonc", text = ""},
	{ name = "toml", text = ""},
	{ name = "xml", text = "󰗀"},
	{ name = "yaml", text = ""},
	{ name = "yml", text = ""},

	# Databases
	{ name = "db", text = ""},
	{ name = "sql", text = ""},
	{ name = "sqlite", text = ""},
	{ name = "sqlite3", text = ""},

	# Config Extentions
	{ name = "cfg", text = ""},
	{ name = "conf", text = ""},
	{ name = "rasi", text = ""}, # for Rofi

	# Logs
	{ name = "log", text = ""},

	# Systemd Unit Files
	{ name = "timer", text = ""},
	{ name = "service", text = ""},

	# Compressed Files
	{ name = "zip", text = ""},
	{ name = "7z", text = ""},
	{ name = "rar", text = ""},
]

# Order Matters. It's basically an if/else statement
conds = [
	{ if = "hidden & dir", text = "󱞞" }, # hidden directories
	{ if = "hidden & !dir", text="󰘓" },	 # hidden files
	{ if = "link & dir", text="", fg="#57b9bd"},     # symlink directories
	{ if = "link & !dir", text="", fg="#57b9bd"},    # symlink files
	{ if = "dir", text="" },            # directories
	{ if = "!dir & exec", text = "" },  # executable files
	{ if = "!dir", text = "" },         # files
]
