import = [
	#"~/.config/alacritty/themes/themes/breeze.toml"
	#"~/.config/alacritty/themes/themes/breeze_custom.toml" #(Includes the light blue color for fastfetch)
	
	#"~/.config/alacritty/themes/themes/enfocado_dark.toml"
	#"~/.config/alacritty/themes/themes/alabaster_dark.toml"
	#"~/.config/alacritty/themes/themes/aura.toml"
	#"~/.config/alacritty/themes/themes/ayu_dark.toml"
	#"~/.config/alacritty/themes/themes/blood_moon.toml"
	#"~/.config/alacritty/themes/themes/carbonfox.toml"
	#"~/.config/alacritty/themes/themes/hyper.toml"

	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal.family = "0xProto Nerd Font Mono"
size = 12

[env]
TERM = "xterm-256color"

[scrolling]
multiplier = 3
