import = [
	"~/.config/alacritty/themes/themes/breeze.toml"
	#"~/.config/alacritty/themes/themes/enfocado_dark.toml"
	#"~/.config/alacritty/themes/themes/alabaster_dark.toml"
	#"~/.config/alacritty/themes/themes/aura.toml"
	#"~/.config/alacritty/themes/themes/ayu_dark.toml"
	#"~/.config/alacritty/themes/themes/blood_moon.toml"
	#"~/.config/alacritty/themes/themes/carbonfox.toml"
	#"~/.config/alacritty/themes/themes/hyper.toml" (Perfect blue color for Arch logo)
]

working_directory = "/home/abubakr/Desktop"

[font]
normal.family = "0xProto Nerd Font Mono"
size = 12
