[colors]
background = #222729
background-alt = #373B41
foreground = #dbd9d9
primary = #80c9ed
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/status_bar]
bottom=true

width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin = 2

separator = |
separator-foreground = ${colors.disabled}

font-0 = Helvetica Mono:size=12;2
font-1 = 0xProto Nerd Font:size=14;2

;-----------------------------------------
modules-left = updates-pacman-aurhelper system-bluetooth-bluetoothctl
modules-center = xworkspaces 
modules-right = storage battery pulseaudio wlan eth date systray
;-----------------------------------------

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 3

label-occupied = %name%
label-occupied-padding = 3

label-urgent = %name%
;label-urgent-background = ${colors.alert}
label-urgent-underline = ${colors.alert}
label-urgent-padding = 3

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %d %b %Y %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

;---------------------------------------

[module/battery]
type= internal/battery
low-at = 15
battery = BAT

[module/updates-pacman-aurhelper]
type = custom/script
exec = ~/.config/polybar/extra_modules/updates-pacman-aurhelper.sh
interval = 600

[module/system-bluetooth-bluetoothctl]
type = custom/script
exec = ~/.config/polybar/extra_modules/system-bluetooth-bluetoothctl.sh
tail = true
click-left = ~/.config/polybar/extra_modules/system-bluetooth-bluetoothctl.sh --toggle &

[module/storage]
type = custom/ipc
interval = 600

hook-0 = echo $(df -h / --output="used" | awk "NR==2") used of $(df -h / --output="size" | awk "NR==2")
hook-1 = ~/.config/polybar/my_scripts/storage_format_1.sh

initial = 1

click-left = "#storage.hook.0"
click-right = "#storage.hook.1"

label-foreground = ${colors.primary}

;---------------------------------------

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
